version: '3.8'

services:
  sso-auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "44044:44044"
    networks:
      - app-network
    environment:
      - CGO_ENABLED=1
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped  # Автоматический перезапуск при падении

  postgres:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/ssl:/ssl  # Папка с сертификатами
    command: >
      sh -c '
      apk add --no-cache openssl && 
      if [ ! -f /ssl/server.crt ]; then
        openssl req -new -x509 -nodes -out /ssl/server.crt -keyout /ssl/server.key -subj "/CN=postgres"
      fi &&
      docker-entrypoint.sh postgres 
      -c ssl=on 
      -c ssl_cert_file=/ssl/server.crt 
      -c ssl_key_file=/ssl/server.key'
    ports:
      - "5433:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth-service"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: