version: '3.8'

services:
  sso-auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "44044:44044"
    networks:
      - app-network
    environment:
      - CGO_ENABLED=1
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped  # Автоматический перезапуск при падении

  postgres:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth-service"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: